### ISSUE TITLE
TypeError: a bytes-like object is required, not 'int'

### ISSUE THREAD

**Issue by sandwich-destroyer** [vysecurity/LinkedInt#21]
'''
Version: 1.1 FIXED - March 27, 2021
Author: Vincent Yiu @vysecurity

[*] Enter search Keywords (use quotes for more precise results)
company

[*] Enter filename for output (exclude file extension)
company

[*] Filter by Company? (Y/N): 
Y

[*] Specify a Company ID (Provide ID or leave blank to automate): 

[*] Enter e-mail domain suffix (eg. contoso.com): 
company.com

[*] Select a prefix for e-mail generation (auto,full,firstlast,firstmlast,flast,firstl,first.last,fmlast,lastfirst,first): 
flast

[*] Obtained new session
[Notice] Found company ID: 102293

[*] Using company ID: 102293
https://www.linkedin.com/voyager/api/search/cluster?count=40&guides=List(v->PEOPLE,facetCurrentCompany->1337)&origin=OTHER&q=guided&start=0
[*] 794 Results Found
[*] Fetching 20 Pages

[*] Fetching page 0 with 40 results
[*] No picture found for This Dude, Head of Information Security
Traceback (most recent call last):
  File "LinkedInt.py", line 431, in <module>
    get_search()
  File "LinkedInt.py", line 314, in get_search
    f.writelines(newcsv.encode())
TypeError: a bytes-like object is required, not 'int'

'''

**Comment by ipSlav** [comment]
I've solved the issue by doing a basic modifying line 314 from _f.writelines(newcsv.encode())_ to _f.write(newcsv.encode())_

**Comment by vysecurity** [comment]
Great! I'll take a look. Thanks for the feedback.
