### ISSUE TITLE
KeyError: 'location'

### ISSUE THREAD

**Issue by Qu4kE** [vysecurity/LinkedInt#23]
[*] Enter search Keywords (use quotes for more precise results)
"company"

[*] Enter filename for output (exclude file extension)
company

[*] Filter by Company? (Y/N): 
y

[*] Specify a Company ID (Provide ID or leave blank to automate): 

[*] Enter e-mail domain suffix (eg. contoso.com): 
company.com

[*] Select a prefix for e-mail generation (auto,full,firstlast,firstmlast,flast,firstl,first.last,fmlast,lastfirst,first): 
first.last

[*] Obtained new session

[*] Using company ID: 123456789
https://www.linkedin.com/voyager/api/search/cluster?count=40&guides=List(v->PEOPLE,facetCurrentCompany->123456789)&origin=OTHER&q=guided&start=0
[*] 173 Results Found
[*] Fetching 5 Pages

[*] Fetching page 0 with 40 results
Traceback (most recent call last):
  File "LinkedInt.py", line 431, in <module>
    get_search()
  File "LinkedInt.py", line 218, in get_search
    data_location = c['hitInfo']['com.linkedin.voyager.search.SearchProfile']['location']
KeyError: 'location'

**Comment by eaneatfruit** [comment]
+1 on this error as well.
