### ISSUE TITLE
KeyError: 'data'

### ISSUE THREAD

**Issue by steepens** [vysecurity/LinkedInt#26]
Keyerror is crashing program. I installed the latest using git clone and pip install -r requirements.txt. Here's the error:

┌──(steve㉿kali)-[~/Pictures/LinkedInt]
└─$ python3 LinkedInt.py                                                

██╗     ██╗███╗   ██╗██╗  ██╗███████╗██████╗ ██╗███╗   ██╗████████╗
██║     ██║████╗  ██║██║ ██╔╝██╔════╝██╔══██╗██║████╗  ██║╚══██╔══╝
██║     ██║██╔██╗ ██║█████╔╝ █████╗  ██║  ██║██║██╔██╗ ██║   ██║   
██║     ██║██║╚██╗██║██╔═██╗ ██╔══╝  ██║  ██║██║██║╚██╗██║   ██║   
███████╗██║██║ ╚████║██║  ██╗███████╗██████╔╝██║██║ ╚████║   ██║   
╚══════╝╚═╝╚═╝  ╚═══╝╚═╝  ╚═╝╚══════╝╚═════╝ ╚═╝╚═╝  ╚═══╝   ╚═╝   
                                                                   

Version: 1.1 FIXED - March 27, 2021
Author: Vincent Yiu @vysecurity

[*] Enter search Keywords (use quotes for more precise results)
"International Business Machines"     

[*] Enter filename for output (exclude file extension)
ibm

[*] Filter by Company? (Y/N): 
Y

[*] Specify a Company ID (Provide ID or leave blank to automate): 

[*] Enter e-mail domain suffix (eg. contoso.com): 
uk.ibm.com

[*] Select a prefix for e-mail generation (auto,full,firstlast,firstmlast,flast,firstl,first.last,fmlast,lastfirst,first): 
auto

[*] Automatically using Hunter IO to determine best Prefix
Traceback (most recent call last):
  File "/home/steve/Pictures/LinkedInt/LinkedInt.py", line 410, in <module>
    prefix = content['data']['pattern']
KeyError: 'data'

**Comment by MikJagger** [comment]
+1 for this error

don't use the /bypass the HunterIO check to bypass the error (don't use auto prefix).

**Comment by shfsepiol** [comment]
Getting the same error when selecting auto
choosing full gives a whole list of other errors as well

**Comment by johnneerdael** [comment]
Same issues here, both with auto (same error), but flast aswell:
```
Traceback (most recent call last):
  File "/Users/johnneerdael/Scripts/LinkedInt/LinkedInt.py", line 431, in <module>
    get_search()
  File "/Users/johnneerdael/Scripts/LinkedInt/LinkedInt.py", line 146, in get_search
    r = requests.get(url, cookies=cookies, headers=headers)
  File "/opt/homebrew/lib/python3.9/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/requests/sessions.py", line 659, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/opt/homebrew/lib/python3.9/site-packages/requests/sessions.py", line 659, in <listcomp>
    history = [resp for resp in gen] if allow_redirects else []
  File "/opt/homebrew/lib/python3.9/site-packages/requests/sessions.py", line 156, in resolve_redirects
    raise TooManyRedirects('Exceeded %s redirects.' % self.max_redirects, response=resp)
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.
```

**Comment by Synernog** [comment]
+1 Same issue:

[*] Enter search Keywords (use quotes for more precise results)
"general motors"

[*] Enter filename for output (exclude file extension)
gm

[*] Filter by Company? (Y/N):
Y

[*] Specify a Company ID (Provide ID or leave blank to automate):

[*] Enter e-mail domain suffix (eg. contoso.com):
gm.com

[*] Select a prefix for e-mail generation (auto,full,firstlast,firstmlast,flast,firstl,first.last,fmlast,lastfirst,first):
auto

[*] Automatically using Hunter IO to determine best Prefix
Traceback (most recent call last):
File "/home/steve/Pictures/LinkedInt/LinkedInt.py", line 410, in
prefix = content['data']['pattern']
KeyError: 'data'

**Comment by M3dS0** [comment]
Same Here

**Comment by ryanpoh** [comment]
+1
