### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by i-am-internet** [vysecurity/LinkedInt#4]
This has worked for me so far with smaller companies, but I'm trying to run this for a company with 812 employees and getting this error:
```
Traceback (most recent call last):
  File "LinkedInt.py", line 429, in <module>
    get_search()
  File "LinkedInt.py", line 202, in get_search
    print "[*] Fetching page %i with %i results" % ((p),len(content['elements'][0]['elements']))
IndexError: list index out of range
```

**Comment by vysecurity** [comment]
Fixed. Feel free to sponsor open source research at https://github.com/sponsors/vysecurity
