### ISSUE TITLE
KeyError: 'elements'

### ISSUE THREAD

**Issue by gigaflopper** [vysecurity/LinkedInt#9]
Traceback (most recent call last):
  File "LinkedInt.py", line 414, in <module>
    get_search()
  File "LinkedInt.py", line 122, in get_search
    for i in range(0,len(content['elements'])):
KeyError: 'elements'

**Comment by vysecurity** [comment]
Fixed. Feel free to sponsor open source research at https://github.com/sponsors/vysecurity

**Comment by adelinglibert** [comment]
Hi @vysecurity , I ran into the same error 

Traceback (most recent call last):
  File "LinkedInt.py", line 431, in <module>
    get_search()
  File "LinkedInt.py", line 149, in get_search
    for i in range(0,len(content['elements'])):
KeyError: 'elements'
